version: '3'
services:
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - "mc-data:/var/lib/postgresql/data"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/manageContace
    ports:
      - "3000:3000"
    depends_on:
      - db
  proxy:
    build: containers/nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  mc-data:
    external: true